### PR TITLE
Name reference saved to Resources

### PR DESCRIPTION
**Pull request by Papsnoek**
In my middleware, I am persisting to LevelDB store. I need to know which "Resource" to store to when the stack is called.

This was the only way I could figure it out.

"req.resource.name" , then we know this must go to the "messages" SubDB as an example.

### CODE REVIEW

**Comment by scttnlsn** [comment]
Great.  Thanks!

**Comment by scttnlsn** [comment]
Available in v0.3.1

**Comment by Papsnoek** [comment]
Woot, My first ever commit.

I am still neatening up my LevelDB middleware for persistence. I will share this when I get back from holiday if you would like to use it as a middleware for Data.IO :)

**Comment by scttnlsn** [comment]
Awesome!  You should publish your LevelDB middleware to NPM.

**Pull request merged**
